---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocrawlernews
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gocrawlernews
    spec:
      containers:
      - name: gocrawler
        image: bronzels/gocrawler:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: BIND_PORT
          value: "50058"
        - name: BIND_IP
          value: "0.0.0.0"
        ports:
        - containerPort: 50058
        command: [ "/go/bin/crawlnewsserver"]
