---
apiVersion: v1
kind: Service
metadata:
  name: gocrawlernews
  labels:
    type: grpc
    service: gocrawlernews
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50058
    nodePort: 30092
  selector:
    name: gocrawlernews
